export { default as Error404 } from "./ErrorPage/Error404";
export { default as HomePage } from "./HomePage/HomePage";
export { default as ProductPage } from "./ProductPage/ProductPage";
export { default as ProductListPage } from "./ProductListPage/ProductListPage";
export { default as UserPage } from "./UserPage/UserPage";
export { default as RecipeListPage } from "./recipes/RecipeListPage";
export { default as RecipePage } from "./recipes/RecipePage";
export { default as HikingListPage } from "./hikings/HikingListPage";
export { default as HikingPage } from "./hikings/HikingPage";
